<?xml version="1.0"?>
<package format="2">
  <name>ben_project11</name>
  <version>0.0.0</version>
  <description>
    Launch files and configuration for BEN, the Bathymetric Explorer and Navigator.
  </description>

  <author email="roland@ccom.unh.edu">Roland Arsenault</author>
  <maintainer email="roland@ccom.unh.edu">Roland Arsenault</maintainer>

  <license>BSD</license>

  <buildtool_depend>ament_cmake_ros</buildtool_depend>
  <exec_depend>project11</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>
