/**/mru_transform:
  ros__parameters:
    sensors:
      nav:
        topics:
          orientation: "sensors/nav/orientation"
          position: "sensors/nav/position"
          velocity: "sensors/nav/velocity"
    sensor_names:
    - nav

/**/platform_sender:
  ros__parameters:
    nav:
      source_names:
        - nav
      sources:
        nav:
          topics:
            orientation: "sensors/nav/orientation"
            position: "sensors/nav/position"
            velocity: "sensors/nav/velocity"

/**/udp_bridge:
  ros__parameters:
    name: ben
    remotes:
      operator:
        connections:
          default:
            topics:
              nav_position: {source: sensors/nav/position}
              nav_orientation: {source: sensors/nav/orientation}
              nav_velocity: {source: sensors/nav/velocity}
